package test;

import io.qameta.allure.Step;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import test.pages.SearchHotelPage;
import test.utils.ScreenshotUtils;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class BaseTest {

    public static final String BASE_APP_URL = "https://www.booking.com/index.uk.html";
    public static final String REGISTER_URL = "https://account.booking.com/register?op_token=EgVvYXV0aCKLCwoUdk8xS2Jsazd4WDl0VW4yY3BaTFMSCWF1dGhvcml6ZRo1aHR0cHM6Ly9zZWN1cmUuYm9va2luZy5jb20vbG9naW4uaHRtbD9vcD1vYXV0aF9yZXR1cm4qqgpVdHdIMWVLS0xvckdiVGstVUZ4Y1RzY19FbC1OVVVpRFNZT3ZOd19Sa0JGVXRaTHZHT2JSWmhwLXRkelFkSVdmSVg2MFBsSnhVZFZ3b2Z0ZUdHM2dYeFI4Q2JNLVdtSFpGZjN1SHVHNHc0d0lQSzVfZVRFMzNfNDdmb1RjejkyUFExUDRkY2J6Q2NxQm5LeVM4dDNoTG9wU2VQa1NWSjFVbzNmZ0RrTkljU0JRX1BmS2hqci0xZkFHNHR2TVNTaDFTeE1YUWFGX29HN0cyR3luc0JGaUJLRGZyZlM2dWZ0cE1lTXVJNWc4RVlQRlRnbG81UVBHamFqU19pY1RRZHB3ZGV0NXc3ZUxhaGxMLU1DaEdXM001cTd5UlV4WlN4N1I4aEpCLVVDVV9GcUUwUVVNWkRuWHFXUWctTGlSVV9QaHYxbVpyaWNTcWo4VFBCd0JRSUJvYThsQzRhOXlabHdCYmswQVNQZ1dIeU53dkRmOTdyOVdQcFpoa05RTXE0OWVDLUdKX2xfaDZpNE04d0NtZnNEREV4SERna2hjZHVhbGJOVlZpMnpKSUp4bDI2bTZrZTZzWFFnc09iVnJvMFpUTWdOUEZiSGZTTHZxQzJ6aVpXdWJPVTdQTmh6NE5UX0tJY0p6S2FIVk82R201aGxhVGoyUDJsRmxkenUybmFFVTlWN2lVZUJGbUpUQjVFWFl1N05fOUFLVnVwLUVLX3BTRWlrNmdzT3l1RDBncElxVk1faExVNGtHM251SEJ6YWpNb25ZSXFjN18zdmcySzJndWI0LWpUbmE0a3dxbzNmUHgyeGlUSjUwdFVLT2tRYUFRWk5ybVdRNmh5cmEyX3o5SFlTMjlKVjFFZkFmUWg4YTM4R01pckFHUHdvRTFLLUxyUGJoY2tJUThFWEZrMmFGb19leFhaS05MUXRabG5XRHVOQk9fV3lPLTVrcXpvV010WnBWaXdiNi1UenBRRW15bW1COGNjM1FWSnhmQ3ByT2FEQmNOak13TmtlOFZYS09oMkx6TU0wYm1ZMkl2NkdFZXRiZlE2WG1ibW53MTdta1B4WVptZE9NcmFneWVmbWhVZzlPY2JkVnpMbVVuNFloSXFKWEdSSGFxU2RiRHV3TXRHdFRfaTRoUjJoRmdLOHZkOTM2Q0E3emNtdFJqRmVhd3c0WEprMllhQ09CdGFKekcyaXJDakY1ZmlnSHdwc1hBYjBUcUljNEUyY21saXlzblpvZk1UVWEyODJDNWNzX3RaeUpBX1hPcEwzUzZicmRHRlZNRWlIcGQyNDVEWDQ3My1JUFAyWjg4RDFXXzZlODVQMGl4bDd6MVVuNHZPeTladGgxWU1vbGRFQ0dENFplMzBPN29DdmE5bVNlZHJsSWJwbDJVOUh0eHRZcGl2a0x2SVdoYWFXN3o0eTJKSjNHcWVDS3VUMC1EMUtlenlqbXZvZzJiOEpDNXpTdkVGRDlqRGNZZkV2NExzMzFnX1oxTmxSc0NEX05pa3hJZEZNaEZCUWJCU3JhZnhtMjNFYVVUOFRBVWRrUDhLbmEtR0dsZThCdk84endYakM2OGhFRHVFM3JTWHpsQzV2bENKLWJnYy1PUUhDSmxpM3J6clRWZl9LZmhwdDN4c3M3bHc5c0hOazluZEtqY2lTS24tZkF3TkNVNVhCMTVQcElHVzhVcHRIQ29lR3llRk5nN0wxbWc1Qy1YaG41bVJOZXJjNXUyTC1VUzdsVWdDVFlLRVFtN2JfMzhsc2hnZ0IEY29kZSoOCI7IEjoAQgBY5dPa7gU";
    public static final String SIGH_IN_URL = "https://account.booking.com/sign-in?op_token=EgVvYXV0aCKLCwoUdk8xS2Jsazd4WDl0VW4yY3BaTFMSCWF1dGhvcml6ZRo1aHR0cHM6Ly9zZWN1cmUuYm9va2luZy5jb20vbG9naW4uaHRtbD9vcD1vYXV0aF9yZXR1cm4qqgpVdHdIMWVLS0xvckdiVGstVUZ4Y1RzY19FbC1OVVVpRFNZT3ZOd19Sa0JGVXRaTHZHT2JSWmhwLXRkelFkSVdmSVg2MFBsSnhVZFZ3b2Z0ZUdHM2dYeFI4Q2JNLVdtSFpGZjN1SHVHNHc0d0lQSzVfZVRFMzNfNDdmb1RjejkyUFExUDRkY2J6Q2NxQm5LeVM4dDNoTG9wU2VQa1NWSjFVbzNmZ0RrTkljU0JRX1BmS2hqci0xZkFHNHR2TVNTaDFTeE1YUWFGX29HN0cyR3luc0JGaUJLRGZyZlM2dWZ0cE1lTXVJNWc4RVlQRlRnbG81UVBHamFqU19pY1RRZHB3ZGV0NXc3ZUxhaGxMLU1DaEdXM001cTd5UlV4WlN4N1I4aEpCLVVDVV9GcUUwUVVNWkRuWHFXUWctTGlSVV9QaHYxbVpyaWNTcWo4VFBCd0JRSUJvYThsQzRhOXlabHdCYmswQVNQZ1dIeU53dkRmOTdyOVdQcFpoa05RTXE0OWVDLUdKX2xfaDZpNE04d0NtZnNEREV4SERna2hjZHVhbGJOVlZpMnpKSUp4bDI2bTZrZTZzWFFnc09iVnJvMFpUTWdOUEZiSGZTTHZxQzJ6aVpXdWJPVTdQTmh6NE5UX0tJY0p6S2FIVk82R201aGxhVGoyUDJsRmxkenUybmFFVTlWN2lVZUJGbUpUQjVFWFl1N05fOUFLVnVwLUVLX3BTRWlrNmdzT3l1RDBncElxVk1faExVNGtHM251SEJ6YWpNb25ZSXFjN18zdmcySzJndWI0LWpUbmE0a3dxbzNmUHgyeGlUSjUwdFVLT2tRYUFRWk5ybVdRNmh5cmEyX3o5SFlTMjlKVjFFZkFmUWg4YTM4R01pckFHUHdvRTFLLUxyUGJoY2tJUThFWEZrMmFGb19leFhaS05MUXRabG5XRHVOQk9fV3lPLTVrcXpvV010WnBWaXdiNi1UenBRRW15bW1COGNjM1FWSnhmQ3ByT2FEQmNOak13TmtlOFZYS09oMkx6TU0wYm1ZMkl2NkdFZXRiZlE2WG1ibW53MTdta1B4WVptZE9NcmFneWVmbWhVZzlPY2JkVnpMbVVuNFloSXFKWEdSSGFxU2RiRHV3TXRHdFRfaTRoUjJoRmdLOHZkOTM2Q0E3emNtdFJqRmVhd3c0WEprMllhQ09CdGFKekcyaXJDakY1ZmlnSHdwc1hBYjBUcUljNEUyY21saXlzblpvZk1UVWEyODJDNWNzX3RaeUpBX1hPcEwzUzZicmRHRlZNRWlIcGQyNDVEWDQ3My1JUFAyWjg4RDFXXzZlODVQMGl4bDd6MVVuNHZPeTladGgxWU1vbGRFQ0dENFplMzBPN29DdmE5bVNlZHJsSWJwbDJVOUh0eHRZcGl2a0x2SVdoYWFXN3o0eTJKSjNHcWVDS3VUMC1EMUtlenlqbXZvZzJiOEpDNXpTdkVGRDlqRGNZZkV2NExzMzFnX1oxTmxSc0NEX05pa3hJZEZNaEZCUWJCU3JhZnhtMjNFYVVUOFRBVWRrUDhLbmEtR0dsZThCdk84endYakM2OGhFRHVFM3JTWHpsQzV2bENKLWJnYy1PUUhDSmxpM3J6clRWZl9LZmhwdDN4c3M3bHc5c0hOazluZEtqY2lTS24tZkF3TkNVNVhCMTVQcElHVzhVcHRIQ29lR3llRk5nN0wxbWc1Qy1YaG41bVJOZXJjNXUyTC1VUzdsVWdDVFlLRVFtN2JfMzhsc2hnZ0IEY29kZSoOCI7IEjoAQgBY5dPa7gUn";

    WebDriver webDriver;
    ScreenshotUtils screen = new ScreenshotUtils();

    @Step
    @BeforeTest
    public void setUp() {
//        webDriver = new ChromeDriver();
        DesiredCapabilities capabilities = DesiredCapabilities.chrome();
        try {
            webDriver = new RemoteWebDriver(new URL("http://10.65.146.65:4444/wd/hub"), capabilities);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        webDriver.manage().timeouts().implicitlyWait(90, TimeUnit.SECONDS);
        webDriver.get(BASE_APP_URL);
        webDriver.manage().window().maximize();
    }

    @Step
    public void clearCookiesAndSetUaLang() {
        webDriver.manage().deleteAllCookies();
        webDriver.get(BASE_APP_URL);
        SearchHotelPage searchHotelPage = new SearchHotelPage(webDriver);
        searchHotelPage.setEurCurrency();
    }

    @Step
    @AfterTest
    public void ShutDown() {
        webDriver.quit();
    }

}
